# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abbb008368e948d5cf6133a566c9fc524370278581e332ffb05b59936231bc47d65c058ef6ee548f14ea64bf41484ac1ab762126a5e999dacb1ad64b085da811

test:
  secret_key_base: 7011620166ee14c9e776c612c8114c07f62de6fa8d72a8601a02b6100a25d77c07a4e5d8a760677da37bc104839f187c224db3b3aa37db1e9822ca00a12d27a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
